### ISSUE TITLE
BUG: Attempt to lauch Editor on Win10 x64 using x64 version crashes.

### ISSUE THREAD

**Issue by krukhlis** [ja2-stracciatella/ja2-stracciatella#1354]
[ja2-launcher.log](https://github.com/ja2-stracciatella/ja2-stracciatella/files/6360785/ja2-launcher.log)
[ja2.log](https://github.com/ja2-stracciatella/ja2-stracciatella/files/6360786/ja2.log)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  0.18 pre-release or 0.17| JA2 Gold English |    no    |    no     |

From the launcher try to launch editor( data folder location is already specified). It will play video animation, press space to skip animation and then it crashes:
![image](https://user-images.githubusercontent.com/18131621/115773732-a4bd2c80-a37e-11eb-994f-fffc9f48a9f6.png)

The same behaviour is 100% reproducable in 0.17 release and 0.18 pre-release.
I'm using the following Windows version: https://storage.googleapis.com/ja2-builds/nightlies/ja2-stracciatella_0.18.0-20210422+d30318a/ja2-stracciatella_0.18.0-20210422+d30318a_win-msvc64-142.zip

( and similar for 0.17).
Please find logs from 0.17 version attached( 0.18 has the same information).

**Comment by lynxlynxlynx** [comment]
You have no luck, this is also reported already #1347. Third issue from the top ...

**Comment by lynxlynxlynx** [comment]
Try the next available build, once it is up — the fix has been pushed.

**Comment by krukhlis** [comment]
:) Well, don't think I'm submitting bugs just to flood the bugs list.
As far as I remember AppImage is a Linux package&run&distribute system. But I am experiencing these issues in Windows. With both 0.17 and 0.18 pre-release versions, so it's not a new bug.

**Comment by selaux** [comment]
Yep, I think it affected both Windows and Linux builds not only AppImage. The location of the free `editor.slf` file was wrong in both cases. I'll paste the new build here when available and we can reopen when there is still an issue.

**Comment by selaux** [comment]
Here is the new build: https://storage.googleapis.com/ja2-builds/releases/v0.18.0/ja2-stracciatella_0.18.0-git+256e4d2_win-msvc64-142.zip

**Comment by krukhlis** [comment]
@selaux Thank you for the prompt build. I've downloaded and checked -- everything works like a charm on 2 different Win10 laptops. I can confirm the issue is fixed.
